/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadOldRouteImport } from './routes/upload-old'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as TracksRouteRouteImport } from './routes/tracks/route'
import { Route as MixesRouteRouteImport } from './routes/mixes/route'
import { Route as LabelsRouteRouteImport } from './routes/labels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracksIndexRouteImport } from './routes/tracks/index'
import { Route as MixesIndexRouteImport } from './routes/mixes/index'
import { Route as LabelsIndexRouteImport } from './routes/labels/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TracksTrackIdRouteImport } from './routes/tracks/$trackId'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as ReleasesSlugRouteImport } from './routes/releases/$slug'
import { Route as MixesMixIdRouteImport } from './routes/mixes/$mixId'
import { Route as LabelsLabelSlugRouteImport } from './routes/labels/$labelSlug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const UploadLazyRouteImport = createFileRoute('/upload')()
const MixUploadLazyRouteImport = createFileRoute('/mix-upload')()
const LabelUploadLazyRouteImport = createFileRoute('/label-upload')()

const UploadLazyRoute = UploadLazyRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/upload.lazy').then((d) => d.Route))
const MixUploadLazyRoute = MixUploadLazyRouteImport.update({
  id: '/mix-upload',
  path: '/mix-upload',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/mix-upload.lazy').then((d) => d.Route))
const LabelUploadLazyRoute = LabelUploadLazyRouteImport.update({
  id: '/label-upload',
  path: '/label-upload',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/label-upload.lazy').then((d) => d.Route))
const UploadOldRoute = UploadOldRouteImport.update({
  id: '/upload-old',
  path: '/upload-old',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRouteRoute = TracksRouteRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const MixesRouteRoute = MixesRouteRouteImport.update({
  id: '/mixes',
  path: '/mixes',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsRouteRoute = LabelsRouteRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TracksRouteRoute,
} as any)
const MixesIndexRoute = MixesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MixesRouteRoute,
} as any)
const LabelsIndexRoute = LabelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabelsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdRoute = TracksTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => TracksRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesSlugRoute = ReleasesSlugRouteImport.update({
  id: '/releases/$slug',
  path: '/releases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MixesMixIdRoute = MixesMixIdRouteImport.update({
  id: '/$mixId',
  path: '/$mixId',
  getParentRoute: () => MixesRouteRoute,
} as any)
const LabelsLabelSlugRoute = LabelsLabelSlugRouteImport.update({
  id: '/$labelSlug',
  path: '/$labelSlug',
  getParentRoute: () => LabelsRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/labels': typeof LabelsRouteRouteWithChildren
  '/mixes': typeof MixesRouteRouteWithChildren
  '/tracks': typeof TracksRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/reminders': typeof RemindersRoute
  '/subscribe': typeof SubscribeRoute
  '/upload-old': typeof UploadOldRoute
  '/label-upload': typeof LabelUploadLazyRoute
  '/mix-upload': typeof MixUploadLazyRoute
  '/upload': typeof UploadLazyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/labels/$labelSlug': typeof LabelsLabelSlugRoute
  '/mixes/$mixId': typeof MixesMixIdRoute
  '/releases/$slug': typeof ReleasesSlugRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/admin': typeof AdminIndexRoute
  '/labels/': typeof LabelsIndexRoute
  '/mixes/': typeof MixesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/reminders': typeof RemindersRoute
  '/subscribe': typeof SubscribeRoute
  '/upload-old': typeof UploadOldRoute
  '/label-upload': typeof LabelUploadLazyRoute
  '/mix-upload': typeof MixUploadLazyRoute
  '/upload': typeof UploadLazyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/labels/$labelSlug': typeof LabelsLabelSlugRoute
  '/mixes/$mixId': typeof MixesMixIdRoute
  '/releases/$slug': typeof ReleasesSlugRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/admin': typeof AdminIndexRoute
  '/labels': typeof LabelsIndexRoute
  '/mixes': typeof MixesIndexRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/labels': typeof LabelsRouteRouteWithChildren
  '/mixes': typeof MixesRouteRouteWithChildren
  '/tracks': typeof TracksRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/reminders': typeof RemindersRoute
  '/subscribe': typeof SubscribeRoute
  '/upload-old': typeof UploadOldRoute
  '/label-upload': typeof LabelUploadLazyRoute
  '/mix-upload': typeof MixUploadLazyRoute
  '/upload': typeof UploadLazyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/labels/$labelSlug': typeof LabelsLabelSlugRoute
  '/mixes/$mixId': typeof MixesMixIdRoute
  '/releases/$slug': typeof ReleasesSlugRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/admin/': typeof AdminIndexRoute
  '/labels/': typeof LabelsIndexRoute
  '/mixes/': typeof MixesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/labels'
    | '/mixes'
    | '/tracks'
    | '/changelog'
    | '/dashboard'
    | '/reminders'
    | '/subscribe'
    | '/upload-old'
    | '/label-upload'
    | '/mix-upload'
    | '/upload'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/labels/$labelSlug'
    | '/mixes/$mixId'
    | '/releases/$slug'
    | '/settings/profile'
    | '/tracks/$trackId'
    | '/admin'
    | '/labels/'
    | '/mixes/'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/dashboard'
    | '/reminders'
    | '/subscribe'
    | '/upload-old'
    | '/label-upload'
    | '/mix-upload'
    | '/upload'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/labels/$labelSlug'
    | '/mixes/$mixId'
    | '/releases/$slug'
    | '/settings/profile'
    | '/tracks/$trackId'
    | '/admin'
    | '/labels'
    | '/mixes'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/labels'
    | '/mixes'
    | '/tracks'
    | '/changelog'
    | '/dashboard'
    | '/reminders'
    | '/subscribe'
    | '/upload-old'
    | '/label-upload'
    | '/mix-upload'
    | '/upload'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/labels/$labelSlug'
    | '/mixes/$mixId'
    | '/releases/$slug'
    | '/settings/profile'
    | '/tracks/$trackId'
    | '/admin/'
    | '/labels/'
    | '/mixes/'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabelsRouteRoute: typeof LabelsRouteRouteWithChildren
  MixesRouteRoute: typeof MixesRouteRouteWithChildren
  TracksRouteRoute: typeof TracksRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  RemindersRoute: typeof RemindersRoute
  SubscribeRoute: typeof SubscribeRoute
  UploadOldRoute: typeof UploadOldRoute
  LabelUploadLazyRoute: typeof LabelUploadLazyRoute
  MixUploadLazyRoute: typeof MixUploadLazyRoute
  UploadLazyRoute: typeof UploadLazyRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ReleasesSlugRoute: typeof ReleasesSlugRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix-upload': {
      id: '/mix-upload'
      path: '/mix-upload'
      fullPath: '/mix-upload'
      preLoaderRoute: typeof MixUploadLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label-upload': {
      id: '/label-upload'
      path: '/label-upload'
      fullPath: '/label-upload'
      preLoaderRoute: typeof LabelUploadLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-old': {
      id: '/upload-old'
      path: '/upload-old'
      fullPath: '/upload-old'
      preLoaderRoute: typeof UploadOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixes': {
      id: '/mixes'
      path: '/mixes'
      fullPath: '/mixes'
      preLoaderRoute: typeof MixesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels': {
      id: '/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof TracksRouteRoute
    }
    '/mixes/': {
      id: '/mixes/'
      path: '/'
      fullPath: '/mixes/'
      preLoaderRoute: typeof MixesIndexRouteImport
      parentRoute: typeof MixesRouteRoute
    }
    '/labels/': {
      id: '/labels/'
      path: '/'
      fullPath: '/labels/'
      preLoaderRoute: typeof LabelsIndexRouteImport
      parentRoute: typeof LabelsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdRouteImport
      parentRoute: typeof TracksRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$slug': {
      id: '/releases/$slug'
      path: '/releases/$slug'
      fullPath: '/releases/$slug'
      preLoaderRoute: typeof ReleasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixes/$mixId': {
      id: '/mixes/$mixId'
      path: '/$mixId'
      fullPath: '/mixes/$mixId'
      preLoaderRoute: typeof MixesMixIdRouteImport
      parentRoute: typeof MixesRouteRoute
    }
    '/labels/$labelSlug': {
      id: '/labels/$labelSlug'
      path: '/$labelSlug'
      fullPath: '/labels/$labelSlug'
      preLoaderRoute: typeof LabelsLabelSlugRouteImport
      parentRoute: typeof LabelsRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LabelsRouteRouteChildren {
  LabelsLabelSlugRoute: typeof LabelsLabelSlugRoute
  LabelsIndexRoute: typeof LabelsIndexRoute
}

const LabelsRouteRouteChildren: LabelsRouteRouteChildren = {
  LabelsLabelSlugRoute: LabelsLabelSlugRoute,
  LabelsIndexRoute: LabelsIndexRoute,
}

const LabelsRouteRouteWithChildren = LabelsRouteRoute._addFileChildren(
  LabelsRouteRouteChildren,
)

interface MixesRouteRouteChildren {
  MixesMixIdRoute: typeof MixesMixIdRoute
  MixesIndexRoute: typeof MixesIndexRoute
}

const MixesRouteRouteChildren: MixesRouteRouteChildren = {
  MixesMixIdRoute: MixesMixIdRoute,
  MixesIndexRoute: MixesIndexRoute,
}

const MixesRouteRouteWithChildren = MixesRouteRoute._addFileChildren(
  MixesRouteRouteChildren,
)

interface TracksRouteRouteChildren {
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

const TracksRouteRouteChildren: TracksRouteRouteChildren = {
  TracksTrackIdRoute: TracksTrackIdRoute,
  TracksIndexRoute: TracksIndexRoute,
}

const TracksRouteRouteWithChildren = TracksRouteRoute._addFileChildren(
  TracksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabelsRouteRoute: LabelsRouteRouteWithChildren,
  MixesRouteRoute: MixesRouteRouteWithChildren,
  TracksRouteRoute: TracksRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  RemindersRoute: RemindersRoute,
  SubscribeRoute: SubscribeRoute,
  UploadOldRoute: UploadOldRoute,
  LabelUploadLazyRoute: LabelUploadLazyRoute,
  MixUploadLazyRoute: MixUploadLazyRoute,
  UploadLazyRoute: UploadLazyRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ReleasesSlugRoute: ReleasesSlugRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
