/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_VPS_BASE_URL: string
  readonly VITE_PUBLIC_SENTRY_DSN: string
  readonly VITE_PUBLIC_SENTRY_ENVIRONMENT: string
  readonly VITE_PUBLIC_SENTRY_RELEASE: string
  readonly VITE_SPOTIFY_CLIENT_ID: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}