services:
  app:
    build:
      context: .
      target: dev
      dockerfile: vps/Dockerfile
    container_name: bun_app
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user-name:strong-password@db:5433/postgres
    volumes:
      - ./vps:/app/vps
      - ./core:/app/core
      - ./backend:/app/backend
      - ./web:/app/web
    working_dir: /app/vps
    command: bun --hot run src/api/index.ts
    # networks:
    #   - app-network

  db:
    image: postgres
    container_name: gbfm_pgdb
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - gbfm_pgdb:/var/lib/postgresql/data
    # networks:
    #   - app-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user-name
  #     PGADMIN_DEFAULT_PASSWORD: strong-password
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
    # networks:
    #   - app-network

networks:
  app-network:
    driver: bridge

volumes:
  gbfm_pgdb:
  # pgadmin-data: