services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
