/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ACCESS_TOKEN_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiWorker": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "AuthWorkerCF": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "ContentTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "FileRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MDX_Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Mixes": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "REFRESH_TOKEN_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SquealDBUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "User_Content": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "gbfm-www": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "gbfm_network": {
      "type": "sst.aws.Vpc"
    }
    "gbfm_postgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "gbfm_vps": {
      "service": string
      "type": "sst.aws.Service"
    }
    "gbfm_vps_gateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}