/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BlueskySyncTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "CdnRouterWorker": import("@cloudflare/workers-types").Service
    "DatabaseBackups": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DatabaseHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabasePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabasePort": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUser": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "GBFM_ENCRYPTION_ROOT_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Mixes": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MixesR2": import("@cloudflare/workers-types").R2Bucket
    "OTEL_EXPORTER_OTLP_ENDPOINT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OTEL_EXPORTER_OTLP_HEADERS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SENTRY_BACKEND_DSN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SpotifyClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StorageAccessKeyId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StorageEndpoint": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StorageProvider": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StorageRegion": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StorageSecretAccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StorageSigningEndpoint": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Urls": {
      "site": string
      "type": "sst.sst.Linkable"
      "vps": string
    }
    "UserContentR2": import("@cloudflare/workers-types").R2Bucket
    "User_Content": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VITE_PUBLIC_SENTRY_DSN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "gbfm-www": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "gbfm_network": {
      "type": "sst.aws.Vpc"
    }
    "gbfm_vps": {
      "service": string
      "type": "sst.aws.Service"
    }
    "gbfm_vps_gateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}

import "sst"
export {}