import type { IncomingMessage } from 'node:http'
import { sentryVitePlugin } from '@sentry/vite-plugin'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import mdx from '@mdx-js/rollup'
import tailwindcss from '@tailwindcss/vite'
import { repoChangelogPlugin } from './plugins/repo-changelog'
import { themeColorsPlugin } from './plugins/theme-colors'

// VPS_PROXY_TARGET is deliberately not VITE_ prefixed: it steers the dev proxy
// only. Setting VITE_VPS_BASE_URL would also reach the browser bundle, making
// requests cross-site and dropping the session cookie.
const VPS_PROXY_TARGET =
  process.env.VPS_PROXY_TARGET || process.env.VITE_VPS_BASE_URL || 'http://127.0.0.1:3003'
const sentryRelease = process.env.SENTRY_RELEASE
const shouldUploadSourceMaps = Boolean(process.env.SENTRY_AUTH_TOKEN && sentryRelease)

const vpsProxy = {
  target: VPS_PROXY_TARGET,
  changeOrigin: true
}

const isDocumentRequest = (req: IncomingMessage) => {
  const { accept } = req.headers
  return !Array.isArray(accept) && (accept?.includes('text/html') ?? false)
}

const authProxy = {
  ...vpsProxy,
  bypass: (req: IncomingMessage) => (isDocumentRequest(req) ? '/index.html' : undefined)
}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    tailwindcss(),
    themeColorsPlugin(),
    repoChangelogPlugin(),
    {
      enforce: 'pre',
      ...mdx({
        /* jsxImportSource: …, otherOptions… */
      })
    },
    tanstackRouter({ autoCodeSplitting: true }),
    react({ include: /\.(jsx|js|mdx|md|tsx|ts)$/ }),
    ...(shouldUploadSourceMaps
      ? [
          sentryVitePlugin({
            org: 'goosebumps-collective',
            project: 'gbfm-frontend',
            authToken: process.env.SENTRY_AUTH_TOKEN,
            telemetry: false,
            sourcemaps: {
              filesToDeleteAfterUpload: ['./dist/**/*.map']
            },
            release: {
              name: sentryRelease,
              create: true,
              finalize: false,
              setCommits: false,
              deploy: false
            }
          })
        ]
      : [])
  ],
  build: {
    sourcemap: shouldUploadSourceMaps ? 'hidden' : false
  },
  // These imports only occur in a route component generated by TanStack Router's
  // code splitting. Pre-bundle them at startup so loading that route cannot
  // invalidate the optimizer and abort its dynamic import.
  optimizeDeps: {
    include: ['html-to-image', 'react-qr-code']
  },
  resolve: {
    alias: {
      '@': resolve(fileURLToPath(new URL('.', import.meta.url)), 'src')
    }
  },
  server: {
    host: '0.0.0.0',
    allowedHosts: true,
    proxy: {
      '/api': vpsProxy,
      '/auth': authProxy,
      '/health': vpsProxy,
      '/rss.xml': vpsProxy,
      '/sitemap.xml': vpsProxy,
      '/s/': vpsProxy
    }
  }
})
