import { Schema } from 'effect'

/** Content kinds with generated social-card presentations. */
export const SocialCardKind = Schema.Literals([
  'mix',
  'track',
  'release',
  'show',
  'label',
  'profile',
  'editorial',
  'tweet',
])

/** A content kind with a generated social-card presentation. */
export type SocialCardKind = typeof SocialCardKind.Type

/** Image variants generated by the social-card renderer. */
export const SOCIAL_CARD_FORMATS = ['poster', 'sleeve', 'openGraph'] as const

/** A generated social-card image variant. */
export type SocialCardFormat = (typeof SOCIAL_CARD_FORMATS)[number]

/** Formats available to tweet download clients. */
export const TWEET_CARD_FORMATS = SOCIAL_CARD_FORMATS

/** Pixel dimensions of every stable output format. */
export const SOCIAL_CARD_DIMENSIONS = {
  poster: [1080, 1350],
  sleeve: [1080, 1920],
  openGraph: [1200, 630],
} as const satisfies Readonly<Record<SocialCardFormat, readonly [number, number]>>

const NullableString = Schema.NullOr(Schema.String)

/** Runtime contract for an artwork-led Open Graph card. */
export const ArtworkCardModel = Schema.TaggedStruct('ArtworkCard', {
  kind: Schema.Literals(['mix', 'track', 'release']),
  eyebrow: Schema.String,
  title: Schema.String,
  creators: Schema.Array(Schema.String),
  artworkUrl: NullableString,
})

/** Parsed artwork-led card model. */
export type ArtworkCardModel = typeof ArtworkCardModel.Type

/** Runtime contract for a show, label, or profile identity card. */
export const IdentityCardModel = Schema.TaggedStruct('IdentityCard', {
  kind: Schema.Literals(['show', 'label', 'profile']),
  eyebrow: Schema.String,
  title: Schema.String,
  description: Schema.String,
  detail: NullableString,
  imageUrl: NullableString,
})

/** Parsed identity-led card model. */
export type IdentityCardModel = typeof IdentityCardModel.Type

/** Runtime contract for a text-led editorial card. */
export const EditorialCardModel = Schema.TaggedStruct('EditorialCard', {
  kind: Schema.Literal('editorial'),
  title: Schema.String,
  description: Schema.String,
  authors: Schema.Array(Schema.String),
  imageUrl: NullableString,
  publishedLabel: NullableString,
})

/** Parsed editorial card model. */
export type EditorialCardModel = typeof EditorialCardModel.Type

/** Runtime contract consumed by every tweet card renderer. */
export const TweetCardModel = Schema.TaggedStruct('TweetCard', {
  kind: Schema.Literal('tweet'),
  commentary: Schema.String,
  authorName: NullableString,
  username: NullableString,
  avatarUrl: NullableString,
  dateLabel: NullableString,
  entityLabel: NullableString,
  entityTitle: NullableString,
  entityArtists: NullableString,
  coverImageUrl: NullableString,
  url: Schema.String,
})

/** Parsed tweet card model. */
export type TweetCardModel = typeof TweetCardModel.Type

/** Runtime-safe model union crossing the API-to-renderer boundary. */
export const SocialCardModel = Schema.Union([
  ArtworkCardModel,
  IdentityCardModel,
  EditorialCardModel,
  TweetCardModel,
])

/** Parsed social-card model. */
export type SocialCardModel = typeof SocialCardModel.Type

const OpenGraphPresentation = Schema.Struct({
  schemaVersion: Schema.Literal(1),
  revision: Schema.String,
  model: Schema.Union([ArtworkCardModel, IdentityCardModel, EditorialCardModel]),
  images: Schema.Struct({ openGraph: Schema.String }),
})

/** Runtime response contract for a tweet presentation with download formats. */
export const TweetCardPresentation = Schema.Struct({
  schemaVersion: Schema.Literal(1),
  revision: Schema.String,
  model: TweetCardModel,
  images: Schema.Struct({
    poster: Schema.String,
    sleeve: Schema.String,
    openGraph: Schema.String,
  }),
})

/** Parsed tweet share presentation. */
export type TweetCardPresentation = typeof TweetCardPresentation.Type

/** Runtime response contract shared by the API, edge metadata, and renderer. */
export const SocialCardPresentation = Schema.Union([OpenGraphPresentation, TweetCardPresentation])

/** Parsed social-card presentation. */
export type SocialCardPresentation = typeof SocialCardPresentation.Type

/** Source data for an artwork-led card. */
export type ArtworkCardInput = {
  readonly kind: 'mix' | 'track' | 'release'
  readonly slug: string
  readonly title: string
  readonly creators: ReadonlyArray<string>
  readonly imageUrl: string | null
}

/** Source data for an identity-led card. */
export type IdentityCardInput = {
  readonly kind: 'show' | 'label' | 'profile'
  readonly slug: string
  readonly title: string
  readonly description: string
  readonly detail: string | null
  readonly imageUrl: string | null
}

/** Source data for a text-led editorial card. */
export type EditorialCardInput = {
  readonly kind: 'editorial'
  readonly slug: string
  readonly title: string
  readonly description: string
  readonly authors: ReadonlyArray<string>
  readonly imageUrl: string | null
  readonly publishedAt: string | null
}

/** Supported non-tweet social-card source data. */
export type SocialCardInput = ArtworkCardInput | IdentityCardInput | EditorialCardInput

/** Supported music entity input for a tweet card. */
export type TweetCardEntityInput = {
  readonly type: 'album' | 'track' | 'playlist'
  readonly title: string
  readonly artists: ReadonlyArray<string> | null
  readonly coverImageUrl: string | null
}

/** Source data required to create a tweet share presentation. */
export type TweetCardPresentationInput = {
  readonly slug: string
  readonly commentary: string
  readonly createdAt: string
  readonly creator: {
    readonly name: string
    readonly username: string | null
    readonly avatarUrl: string | null
  } | null
  readonly entity: TweetCardEntityInput | null
}

const SITE_URL = 'https://goosebumps.fm'

const templateVersions = {
  ArtworkCard: 'artwork-card-v1',
  IdentityCard: 'identity-card-v1',
  EditorialCard: 'editorial-card-v1',
  TweetCard: 'tweet-card-v2',
} as const satisfies Readonly<Record<SocialCardModel['_tag'], string>>

const eyebrowByKind = {
  mix: 'Mix',
  track: 'Track',
  release: 'Release',
  show: 'Radio show',
  label: 'Record label',
  profile: 'Contributor',
} as const

const entityLabels = {
  album: 'Album',
  track: 'Track',
  playlist: 'Playlist',
} as const satisfies Readonly<Record<TweetCardEntityInput['type'], string>>

const dateFormatter = new Intl.DateTimeFormat('en-US', {
  year: 'numeric',
  month: 'short',
  day: 'numeric',
  timeZone: 'UTC',
})

const revisionFor = async (model: SocialCardModel) => {
  const encoded = new TextEncoder().encode(JSON.stringify([templateVersions[model._tag], model]))
  const digest = await crypto.subtle.digest('SHA-256', encoded)

  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0'))
    .join('')
    .slice(0, 16)
}

const baseUrlFor = (kind: SocialCardKind, slug: string, revision: string) =>
  `${SITE_URL}/social/cards/${kind}/${encodeURIComponent(slug)}/${revision}`

/** Normalizes non-tweet content and derives its immutable Open Graph URL. */
export const buildSocialCardPresentation = async (
  input: SocialCardInput,
): Promise<SocialCardPresentation> => {
  let model: ArtworkCardModel | IdentityCardModel | EditorialCardModel

  switch (input.kind) {
    case 'mix':
    case 'track':
    case 'release':
      model = ArtworkCardModel.make({
        kind: input.kind,
        eyebrow: eyebrowByKind[input.kind],
        title: input.title,
        creators: [...input.creators],
        artworkUrl: input.imageUrl,
      })
      break
    case 'show':
    case 'label':
    case 'profile':
      model = IdentityCardModel.make({
        kind: input.kind,
        eyebrow: eyebrowByKind[input.kind],
        title: input.title,
        description: input.description,
        detail: input.detail,
        imageUrl: input.imageUrl,
      })
      break
    case 'editorial':
      model = EditorialCardModel.make({
        kind: 'editorial',
        title: input.title,
        description: input.description,
        authors: [...input.authors],
        imageUrl: input.imageUrl,
        publishedLabel: input.publishedAt
          ? dateFormatter.format(new Date(input.publishedAt))
          : null,
      })
      break
  }

  const revision = await revisionFor(model)

  return {
    schemaVersion: 1,
    revision,
    model,
    images: { openGraph: `${baseUrlFor(input.kind, input.slug, revision)}/open-graph.png` },
  }
}

/** Normalizes tweet source data and derives immutable URLs for all image formats. */
export const buildTweetCardPresentation = async (
  input: TweetCardPresentationInput,
): Promise<TweetCardPresentation> => {
  const entity = input.entity

  const model: TweetCardModel = TweetCardModel.make({
    kind: 'tweet',
    commentary: input.commentary,
    authorName: input.creator?.name ?? null,
    username: input.creator?.username ?? null,
    avatarUrl: input.creator?.avatarUrl ?? null,
    dateLabel: dateFormatter.format(new Date(input.createdAt)),
    entityLabel: entity ? entityLabels[entity.type] : null,
    entityTitle: entity?.title ?? null,
    entityArtists: entity?.artists?.length ? entity.artists.join(', ') : null,
    coverImageUrl: entity?.coverImageUrl ?? null,
    url: `${SITE_URL}/tweet/${encodeURIComponent(input.slug)}`,
  })

  const revision = await revisionFor(model)
  const base = baseUrlFor('tweet', input.slug, revision)

  return {
    schemaVersion: 1,
    model,
    revision,
    images: {
      poster: `${base}/poster.png`,
      sleeve: `${base}/sleeve.png`,
      openGraph: `${base}/open-graph.png`,
    },
  }
}
