services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./db-data:/var/lib/postgresql/data
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_DB=${DB_NAME}

  app:
    build:
      context: .
      target: dev
    command: bun dev
    ports:
      - 6969:6969
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: .