import { expect, test } from 'vitest'
import { generateCSS, toVars } from './css'
import { brandDark, brandLight } from './tokens/brand'
import { dark, light, studio } from './tokens/shadcn'

function themeBlock(css: string, selector: string): string {
  const start = css.indexOf(selector)
  const end = css.indexOf('\n  }', start)

  expect(start).toBeGreaterThan(-1)
  expect(end).toBeGreaterThan(start)
  return css.slice(start, end)
}

function expectTokenDeclarations<T extends { [K in keyof T]: string }>(
  block: string,
  tokens: T
): void {
  for (const [name, value] of Object.entries(tokens)) {
    if (name === 'backgroundHex') continue
    const property = name.includes('-')
      ? name
      : name.replace(/([A-Z])/g, (letter) => `-${letter.toLowerCase()}`)
    expect(block).toContain(`    --${property}: ${value};`)
  }
}

test('serializes token names and values as indented CSS custom-property declarations', () => {
  expect(toVars({ background: 'red', cardForeground: 'white', 'pastel-green-1': '#b6fadf' })).toBe(
    '    --background: red;\n    --card-foreground: white;\n    --pastel-green-1: #b6fadf;'
  )
  expect(toVars({ highlightRgb: '85, 206, 246' }, '  ')).toBe('  --highlight-rgb: 85, 206, 246;')
})

test('generates complete light, dark, and studio theme blocks from the public token sets', () => {
  const css = generateCSS()

  expect(css).toContain(
    '/* AUTO-GENERATED by packages/theme/src/css.ts — edit token files, not this file */'
  )
  expect(css).toContain('@layer base {')
  expect(css.trimEnd().endsWith('}')).toBe(true)
  expect(css).toContain(':root,\n  .light,\n  [data-theme="light"] {')
  expect(css).toContain('.dark,\n  [data-theme="dark"] {')
  expect(css).toContain('[data-theme="studio"] {')

  const lightBlock = themeBlock(css, '[data-theme="light"]')
  const darkBlock = themeBlock(css, '[data-theme="dark"]')
  const studioBlock = themeBlock(css, '[data-theme="studio"]')

  expectTokenDeclarations(lightBlock, brandLight)
  expectTokenDeclarations(lightBlock, light)
  expectTokenDeclarations(darkBlock, brandDark)
  expectTokenDeclarations(darkBlock, dark)
  expectTokenDeclarations(studioBlock, brandDark)
  expectTokenDeclarations(studioBlock, studio)

  expect(lightBlock).not.toContain('--background-hex:')
  expect(darkBlock).not.toContain('--background-hex:')
  expect(studioBlock).not.toContain('--background-hex:')
  expect(darkBlock.match(/--highlight:/g)).toHaveLength(1)
})
