import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { dark, light, studio, type SemanticTokens } from './tokens/shadcn'
import { brand } from './tokens/brand'

function toKebab(s: string): string {
  if (s.includes('-')) return s
  return s.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

function toVars(obj: Record<string, string>, indent = '    '): string {
  return Object.entries(obj)
    .map(([k, v]) => `${indent}--${toKebab(k)}: ${v};`)
    .join('\n')
}

function semanticToVars(tokens: SemanticTokens, indent = '    '): string {
  const { radius, ...rest } = tokens
  return `${toVars(rest as Record<string, string>, indent)}\n${indent}--radius: ${radius};`
}

const css = `/* AUTO-GENERATED by packages/theme/src/css.ts — edit token files, not this file */

@layer base {
  :root,
  .light,
  [data-theme="light"] {
${toVars(brand as unknown as Record<string, string>)}
${semanticToVars(light)}
  }

  .dark,
  [data-theme="dark"] {
${semanticToVars(dark)}
  }

  [data-theme="studio"] {
${semanticToVars(studio)}
  }
}
`

const outPath = join(import.meta.dir, '..', 'styles', 'theme.css')
writeFileSync(outPath, css, 'utf-8')
console.log('✓ styles/theme.css generated')
