import { brand } from './tokens/brand'
import { dark, light, type SemanticTokens, studio } from './tokens/shadcn'

export function toKebab(s: string): string {
  if (s.includes('-')) return s
  return s.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`)
}

export function toVars<T extends Record<string, string>>(obj: T, indent = '    '): string {
  return Object.entries(obj)
    .map(([k, v]) => `${indent}--${toKebab(k)}: ${v};`)
    .join('\n')
}

export function semanticToVars(tokens: SemanticTokens, indent = '    '): string {
  const { radius, backgroundHex, ...rest } = tokens
  return `${toVars(rest, indent)}\n${indent}--radius: ${radius};`
}

export function generateCSS(): string {
  return `/* AUTO-GENERATED by packages/theme/src/css.ts — edit token files, not this file */

@layer base {
  :root,
  .light,
  [data-theme="light"] {
${toVars(brand)}
${semanticToVars(light)}
  }

  .dark,
  [data-theme="dark"] {
${semanticToVars(dark)}
  }

  [data-theme="studio"] {
${semanticToVars(studio)}
  }
}
`
}
