import { readFile, writeFile } from 'node:fs/promises'

import { Schema } from 'effect'

import { normalizeRichContent } from '../packages/rich-content/src/normalize'
import { parseRichContent } from '../packages/rich-content/src/source'

const ExportRecord = Schema.Struct({
  kind: Schema.String,
  id: Schema.String,
  content: Schema.NullOr(Schema.String),
})

const ExportFile = Schema.Array(ExportRecord)

const [inputPath, outputPath, sqlPath] = process.argv.slice(2)

if (!inputPath) {
  process.stderr.write(
    'Usage: bun scripts/normalize-rich-content.ts <export.json> [normalized.json] [migration.sql]\n',
  )
  process.exit(2)
}

const records = Schema.decodeUnknownSync(ExportFile)(JSON.parse(await readFile(inputPath, 'utf8')))
const unresolved: Array<{ kind: string; id: string; reason: string }> = []
const changes: Array<{ kind: string; id: string; before: string; after: string }> = []
let changed = 0

const normalized = records.map((record) => {
  if (record.content === null || record.content.length === 0) return record
  const result = normalizeRichContent(record.content)

  for (const failure of result.unresolved)
    unresolved.push({ kind: record.kind, id: record.id, reason: failure.reason })

  const diagnostics = parseRichContent(result.source).diagnostics

  for (const diagnostic of diagnostics)
    unresolved.push({ kind: record.kind, id: record.id, reason: diagnostic.message })

  if (result.changed) {
    changed++
    changes.push({ kind: record.kind, id: record.id, before: record.content, after: result.source })
  }

  return { ...record, content: result.source }
})

const report = { records: records.length, changed, unresolved: unresolved.length }
process.stdout.write(`${JSON.stringify(report, null, 2)}\n`)

if (unresolved.length > 0) {
  process.stderr.write(`${JSON.stringify(unresolved, null, 2)}\n`)
  process.exit(1)
}

if (outputPath) await writeFile(outputPath, `${JSON.stringify(normalized, null, 2)}\n`)

if (sqlPath) {
  const tables = new Map([
    ['post', 'posts'],
    ['audio', 'audio'],
    ['show', 'shows'],
    ['release', 'releases'],
    ['label', 'music_labels'],
  ])
  const quoteSql = (value: string) => `'${value.replaceAll("'", "''")}'`
  const statements = changes.map((change) => {
    const table = tables.get(change.kind)

    if (!table) throw new Error(`Cannot generate SQL for content kind: ${change.kind}`)

    return `UPDATE "${table}" SET "content" = ${quoteSql(change.after)} WHERE "id" = ${quoteSql(change.id)} AND "content" = ${quoteSql(change.before)};`
  })

  await writeFile(
    sqlPath,
    [
      '-- Generated by scripts/normalize-rich-content.ts.',
      '-- Updates are idempotent and guarded by the exported source value.',
      `-- Expected changed rows: ${changes.length}`,
      ...statements,
      '',
    ].join('\n'),
  )
}
