<script lang="ts">
  import { Schema } from 'effect'; import Page from '@/lib/components/dashboard/Page.svelte'; import { dashboardJson,jsonRequest } from '@/lib/components/dashboard/api'
  const User=Schema.Struct({id:Schema.String,name:Schema.String,email:Schema.String}); const Users=Schema.Struct({users:Schema.Array(User),total:Schema.Number,limit:Schema.Number,offset:Schema.Number}); const Session=Schema.Struct({id:Schema.String,token:Schema.String,userId:Schema.String,createdAt:Schema.String,expiresAt:Schema.String,userAgent:Schema.optional(Schema.NullOr(Schema.String)),ipAddress:Schema.optional(Schema.NullOr(Schema.String))}); const Sessions=Schema.Struct({sessions:Schema.Array(Session)})
  type UserValue=typeof User.Type; let query=$state(''),results=$state<ReadonlyArray<UserValue>>([]),selected=$state<UserValue|null>(null),sessions=$state<ReadonlyArray<typeof Session.Type>>([]),message=$state('')
  async function search(){try{const q=new URLSearchParams({limit:'10',searchValue:query,searchField:'email'});results=(await dashboardJson(Users,`/auth/admin/list-users?${q}`)).users}catch{message='Search failed.'}}
  async function choose(user:UserValue){selected=user;results=[];try{sessions=(await dashboardJson(Sessions,'/auth/admin/list-user-sessions',jsonRequest('POST',{userId:user.id}))).sessions}catch{message='Could not load sessions.'}}
  async function revoke(path:string,body:Schema.Json){if(!selected)return;try{await dashboardJson(Schema.Unknown,`/auth/admin/${path}`,jsonRequest('POST',body));await choose(selected)}catch{message='Could not revoke session.'}}
  function revokeAll(){if(selected&&confirm('Revoke every session for this user?'))void revoke('revoke-user-sessions',{userId:selected.id})}
</script>
<Page title="Sessions" description="Find a user, inspect active sessions, and revoke access."><form class="flex gap-2" onsubmit={(e)=>{e.preventDefault();void search()}}><input required class="w-full max-w-sm rounded border bg-background p-2" type="email" placeholder="User email" bind:value={query}/><button class="rounded border px-4">Search</button></form>{#each results as user}<button class="mr-2 rounded border p-3 text-left" onclick={()=>void choose(user)}><strong>{user.name}</strong><span class="block text-sm">{user.email}</span></button>{/each}
{#if selected}<section class="space-y-3"><div class="flex justify-between"><h2 class="font-bold">Sessions for {selected.name}</h2>{#if sessions.length}<button class="text-destructive underline" onclick={revokeAll}>Revoke all</button>{/if}</div><div class="overflow-x-auto rounded border"><table class="w-full text-left text-sm"><thead><tr class="bg-muted"><th class="p-3">Created</th><th>Expires</th><th>Device</th><th>IP</th><th></th></tr></thead><tbody>{#each sessions as session}<tr class="border-t"><td class="p-3">{new Date(session.createdAt).toLocaleString()}</td><td>{new Date(session.expiresAt).toLocaleString()}</td><td>{session.userAgent??'Unknown'}</td><td>{session.ipAddress??'—'}</td><td><button class="text-destructive underline" onclick={()=>void revoke('revoke-user-session',{sessionToken:session.token})}>Revoke</button></td></tr>{/each}</tbody></table></div>{#if sessions.length===0}<p>No active sessions.</p>{/if}</section>{/if}{#if message}<p>{message}</p>{/if}</Page>
