/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WordsImport } from './routes/words'
import { Route as TodoImport } from './routes/todo'
import { Route as SubscribeImport } from './routes/subscribe'
import { Route as PostImport } from './routes/post'
import { Route as MixesImport } from './routes/mixes'
import { Route as MicroImport } from './routes/micro'
import { Route as ChangelogImport } from './routes/changelog'
import { Route as ContentListImport } from './routes/_contentList'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as SettingsProfileImport } from './routes/settings/profile'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as ContentListLabelsImport } from './routes/_contentList.labels'
import { Route as ReadArchetypeIdImport } from './routes/read.$archetype.$id'

// Create Virtual Routes

const ContentIndexLazyImport = createFileRoute('/content/')()

// Create/Update Routes

const WordsRoute = WordsImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRoute,
} as any)

const TodoRoute = TodoImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRoute,
} as any)

const SubscribeRoute = SubscribeImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRoute,
} as any)

const PostRoute = PostImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRoute,
} as any)

const MixesRoute = MixesImport.update({
  id: '/mixes',
  path: '/mixes',
  getParentRoute: () => rootRoute,
} as any)

const MicroRoute = MicroImport.update({
  id: '/micro',
  path: '/micro',
  getParentRoute: () => rootRoute,
} as any)

const ChangelogRoute = ChangelogImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRoute,
} as any)

const ContentListRoute = ContentListImport.update({
  id: '/_contentList',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContentIndexLazyRoute = ContentIndexLazyImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/content.index.lazy').then((d) => d.Route))

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileRoute = SettingsProfileImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ContentListLabelsRoute = ContentListLabelsImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => ContentListRoute,
} as any)

const ReadArchetypeIdRoute = ReadArchetypeIdImport.update({
  id: '/read/$archetype/$id',
  path: '/read/$archetype/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_contentList': {
      id: '/_contentList'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ContentListImport
      parentRoute: typeof rootRoute
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogImport
      parentRoute: typeof rootRoute
    }
    '/micro': {
      id: '/micro'
      path: '/micro'
      fullPath: '/micro'
      preLoaderRoute: typeof MicroImport
      parentRoute: typeof rootRoute
    }
    '/mixes': {
      id: '/mixes'
      path: '/mixes'
      fullPath: '/mixes'
      preLoaderRoute: typeof MixesImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostImport
      parentRoute: typeof rootRoute
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeImport
      parentRoute: typeof rootRoute
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoImport
      parentRoute: typeof rootRoute
    }
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsImport
      parentRoute: typeof rootRoute
    }
    '/_contentList/labels': {
      id: '/_contentList/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof ContentListLabelsImport
      parentRoute: typeof ContentListImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/read/$archetype/$id': {
      id: '/read/$archetype/$id'
      path: '/read/$archetype/$id'
      fullPath: '/read/$archetype/$id'
      preLoaderRoute: typeof ReadArchetypeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ContentListRouteChildren {
  ContentListLabelsRoute: typeof ContentListLabelsRoute
}

const ContentListRouteChildren: ContentListRouteChildren = {
  ContentListLabelsRoute: ContentListLabelsRoute,
}

const ContentListRouteWithChildren = ContentListRoute._addFileChildren(
  ContentListRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ContentListRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/micro': typeof MicroRoute
  '/mixes': typeof MixesRoute
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/todo': typeof TodoRoute
  '/words': typeof WordsRoute
  '/labels': typeof ContentListLabelsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/auth': typeof AuthIndexRoute
  '/content': typeof ContentIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ContentListRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/micro': typeof MicroRoute
  '/mixes': typeof MixesRoute
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/todo': typeof TodoRoute
  '/words': typeof WordsRoute
  '/labels': typeof ContentListLabelsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/auth': typeof AuthIndexRoute
  '/content': typeof ContentIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_contentList': typeof ContentListRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/micro': typeof MicroRoute
  '/mixes': typeof MixesRoute
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/todo': typeof TodoRoute
  '/words': typeof WordsRoute
  '/_contentList/labels': typeof ContentListLabelsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/content/': typeof ContentIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/changelog'
    | '/micro'
    | '/mixes'
    | '/post'
    | '/subscribe'
    | '/todo'
    | '/words'
    | '/labels'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/settings/profile'
    | '/auth'
    | '/content'
    | '/read/$archetype/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/changelog'
    | '/micro'
    | '/mixes'
    | '/post'
    | '/subscribe'
    | '/todo'
    | '/words'
    | '/labels'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/settings/profile'
    | '/auth'
    | '/content'
    | '/read/$archetype/$id'
  id:
    | '__root__'
    | '/'
    | '/_contentList'
    | '/changelog'
    | '/micro'
    | '/mixes'
    | '/post'
    | '/subscribe'
    | '/todo'
    | '/words'
    | '/_contentList/labels'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/settings/profile'
    | '/auth/'
    | '/content/'
    | '/read/$archetype/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentListRoute: typeof ContentListRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  MicroRoute: typeof MicroRoute
  MixesRoute: typeof MixesRoute
  PostRoute: typeof PostRoute
  SubscribeRoute: typeof SubscribeRoute
  TodoRoute: typeof TodoRoute
  WordsRoute: typeof WordsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ContentIndexLazyRoute: typeof ContentIndexLazyRoute
  ReadArchetypeIdRoute: typeof ReadArchetypeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentListRoute: ContentListRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  MicroRoute: MicroRoute,
  MixesRoute: MixesRoute,
  PostRoute: PostRoute,
  SubscribeRoute: SubscribeRoute,
  TodoRoute: TodoRoute,
  WordsRoute: WordsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
  ContentIndexLazyRoute: ContentIndexLazyRoute,
  ReadArchetypeIdRoute: ReadArchetypeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_contentList",
        "/changelog",
        "/micro",
        "/mixes",
        "/post",
        "/subscribe",
        "/todo",
        "/words",
        "/auth/forgot-password",
        "/auth/reset-password",
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/verify",
        "/settings/profile",
        "/auth/",
        "/content/",
        "/read/$archetype/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_contentList": {
      "filePath": "_contentList.tsx",
      "children": [
        "/_contentList/labels"
      ]
    },
    "/changelog": {
      "filePath": "changelog.tsx"
    },
    "/micro": {
      "filePath": "micro.tsx"
    },
    "/mixes": {
      "filePath": "mixes.tsx"
    },
    "/post": {
      "filePath": "post.tsx"
    },
    "/subscribe": {
      "filePath": "subscribe.tsx"
    },
    "/todo": {
      "filePath": "todo.tsx"
    },
    "/words": {
      "filePath": "words.tsx"
    },
    "/_contentList/labels": {
      "filePath": "_contentList.labels.tsx",
      "parent": "/_contentList"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx"
    },
    "/settings/profile": {
      "filePath": "settings/profile.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/content/": {
      "filePath": "content.index.lazy.tsx"
    },
    "/read/$archetype/$id": {
      "filePath": "read.$archetype.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
