/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodoImport } from './routes/todo'
import { Route as SubscribeImport } from './routes/subscribe'
import { Route as PostImport } from './routes/post'
import { Route as ChangelogImport } from './routes/changelog'
import { Route as ContentListImport } from './routes/_contentList'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as SettingsProfileImport } from './routes/settings/profile'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthCallbackImport } from './routes/auth/callback'
import { Route as ContentListWordsImport } from './routes/_contentList.words'
import { Route as ContentListMixesImport } from './routes/_contentList.mixes'
import { Route as ContentListMicroImport } from './routes/_contentList.micro'
import { Route as ContentListLabelsImport } from './routes/_contentList.labels'
import { Route as ReadArchetypeIdImport } from './routes/read.$archetype.$id'

// Create Virtual Routes

const ContentIndexLazyImport = createFileRoute('/content/')()

// Create/Update Routes

const TodoRoute = TodoImport.update({
  path: '/todo',
  getParentRoute: () => rootRoute,
} as any)

const SubscribeRoute = SubscribeImport.update({
  path: '/subscribe',
  getParentRoute: () => rootRoute,
} as any)

const PostRoute = PostImport.update({
  path: '/post',
  getParentRoute: () => rootRoute,
} as any)

const ChangelogRoute = ChangelogImport.update({
  path: '/changelog',
  getParentRoute: () => rootRoute,
} as any)

const ContentListRoute = ContentListImport.update({
  id: '/_contentList',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContentIndexLazyRoute = ContentIndexLazyImport.update({
  path: '/content/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/content.index.lazy').then((d) => d.Route))

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileRoute = SettingsProfileImport.update({
  path: '/settings/profile',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  path: '/auth/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const ContentListWordsRoute = ContentListWordsImport.update({
  path: '/words',
  getParentRoute: () => ContentListRoute,
} as any)

const ContentListMixesRoute = ContentListMixesImport.update({
  path: '/mixes',
  getParentRoute: () => ContentListRoute,
} as any)

const ContentListMicroRoute = ContentListMicroImport.update({
  path: '/micro',
  getParentRoute: () => ContentListRoute,
} as any)

const ContentListLabelsRoute = ContentListLabelsImport.update({
  path: '/labels',
  getParentRoute: () => ContentListRoute,
} as any)

const ReadArchetypeIdRoute = ReadArchetypeIdImport.update({
  path: '/read/$archetype/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_contentList': {
      id: '/_contentList'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ContentListImport
      parentRoute: typeof rootRoute
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostImport
      parentRoute: typeof rootRoute
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeImport
      parentRoute: typeof rootRoute
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoImport
      parentRoute: typeof rootRoute
    }
    '/_contentList/labels': {
      id: '/_contentList/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof ContentListLabelsImport
      parentRoute: typeof ContentListImport
    }
    '/_contentList/micro': {
      id: '/_contentList/micro'
      path: '/micro'
      fullPath: '/micro'
      preLoaderRoute: typeof ContentListMicroImport
      parentRoute: typeof ContentListImport
    }
    '/_contentList/mixes': {
      id: '/_contentList/mixes'
      path: '/mixes'
      fullPath: '/mixes'
      preLoaderRoute: typeof ContentListMixesImport
      parentRoute: typeof ContentListImport
    }
    '/_contentList/words': {
      id: '/_contentList/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof ContentListWordsImport
      parentRoute: typeof ContentListImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/read/$archetype/$id': {
      id: '/read/$archetype/$id'
      path: '/read/$archetype/$id'
      fullPath: '/read/$archetype/$id'
      preLoaderRoute: typeof ReadArchetypeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ContentListRouteChildren {
  ContentListLabelsRoute: typeof ContentListLabelsRoute
  ContentListMicroRoute: typeof ContentListMicroRoute
  ContentListMixesRoute: typeof ContentListMixesRoute
  ContentListWordsRoute: typeof ContentListWordsRoute
}

const ContentListRouteChildren: ContentListRouteChildren = {
  ContentListLabelsRoute: ContentListLabelsRoute,
  ContentListMicroRoute: ContentListMicroRoute,
  ContentListMixesRoute: ContentListMixesRoute,
  ContentListWordsRoute: ContentListWordsRoute,
}

const ContentListRouteWithChildren = ContentListRoute._addFileChildren(
  ContentListRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ContentListRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/todo': typeof TodoRoute
  '/labels': typeof ContentListLabelsRoute
  '/micro': typeof ContentListMicroRoute
  '/mixes': typeof ContentListMixesRoute
  '/words': typeof ContentListWordsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/auth': typeof AuthIndexRoute
  '/content': typeof ContentIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ContentListRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/todo': typeof TodoRoute
  '/labels': typeof ContentListLabelsRoute
  '/micro': typeof ContentListMicroRoute
  '/mixes': typeof ContentListMixesRoute
  '/words': typeof ContentListWordsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/auth': typeof AuthIndexRoute
  '/content': typeof ContentIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_contentList': typeof ContentListRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/todo': typeof TodoRoute
  '/_contentList/labels': typeof ContentListLabelsRoute
  '/_contentList/micro': typeof ContentListMicroRoute
  '/_contentList/mixes': typeof ContentListMixesRoute
  '/_contentList/words': typeof ContentListWordsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/content/': typeof ContentIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/changelog'
    | '/post'
    | '/subscribe'
    | '/todo'
    | '/labels'
    | '/micro'
    | '/mixes'
    | '/words'
    | '/auth/callback'
    | '/auth/verify'
    | '/settings/profile'
    | '/auth'
    | '/content'
    | '/read/$archetype/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/changelog'
    | '/post'
    | '/subscribe'
    | '/todo'
    | '/labels'
    | '/micro'
    | '/mixes'
    | '/words'
    | '/auth/callback'
    | '/auth/verify'
    | '/settings/profile'
    | '/auth'
    | '/content'
    | '/read/$archetype/$id'
  id:
    | '__root__'
    | '/'
    | '/_contentList'
    | '/changelog'
    | '/post'
    | '/subscribe'
    | '/todo'
    | '/_contentList/labels'
    | '/_contentList/micro'
    | '/_contentList/mixes'
    | '/_contentList/words'
    | '/auth/callback'
    | '/auth/verify'
    | '/settings/profile'
    | '/auth/'
    | '/content/'
    | '/read/$archetype/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentListRoute: typeof ContentListRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  PostRoute: typeof PostRoute
  SubscribeRoute: typeof SubscribeRoute
  TodoRoute: typeof TodoRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ContentIndexLazyRoute: typeof ContentIndexLazyRoute
  ReadArchetypeIdRoute: typeof ReadArchetypeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentListRoute: ContentListRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  PostRoute: PostRoute,
  SubscribeRoute: SubscribeRoute,
  TodoRoute: TodoRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
  ContentIndexLazyRoute: ContentIndexLazyRoute,
  ReadArchetypeIdRoute: ReadArchetypeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_contentList",
        "/changelog",
        "/post",
        "/subscribe",
        "/todo",
        "/auth/callback",
        "/auth/verify",
        "/settings/profile",
        "/auth/",
        "/content/",
        "/read/$archetype/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_contentList": {
      "filePath": "_contentList.tsx",
      "children": [
        "/_contentList/labels",
        "/_contentList/micro",
        "/_contentList/mixes",
        "/_contentList/words"
      ]
    },
    "/changelog": {
      "filePath": "changelog.tsx"
    },
    "/post": {
      "filePath": "post.tsx"
    },
    "/subscribe": {
      "filePath": "subscribe.tsx"
    },
    "/todo": {
      "filePath": "todo.tsx"
    },
    "/_contentList/labels": {
      "filePath": "_contentList.labels.tsx",
      "parent": "/_contentList"
    },
    "/_contentList/micro": {
      "filePath": "_contentList.micro.tsx",
      "parent": "/_contentList"
    },
    "/_contentList/mixes": {
      "filePath": "_contentList.mixes.tsx",
      "parent": "/_contentList"
    },
    "/_contentList/words": {
      "filePath": "_contentList.words.tsx",
      "parent": "/_contentList"
    },
    "/auth/callback": {
      "filePath": "auth/callback.tsx"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx"
    },
    "/settings/profile": {
      "filePath": "settings/profile.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/content/": {
      "filePath": "content.index.lazy.tsx"
    },
    "/read/$archetype/$id": {
      "filePath": "read.$archetype.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
