/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubscribeImport } from './routes/subscribe'
import { Route as PostImport } from './routes/post'
import { Route as ArchetypeListImport } from './routes/_archetypeList'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthCallbackImport } from './routes/auth/callback'
import { Route as ArchetypeListWordsImport } from './routes/_archetypeList.words'
import { Route as ArchetypeListMixesImport } from './routes/_archetypeList.mixes'
import { Route as ArchetypeListMicroImport } from './routes/_archetypeList.micro'
import { Route as ArchetypeListLabelsImport } from './routes/_archetypeList.labels'
import { Route as ReadArchetypeIdImport } from './routes/read.$archetype.$id'

// Create Virtual Routes

const ArchetypeIndexLazyImport = createFileRoute('/archetype/')()

// Create/Update Routes

const SubscribeRoute = SubscribeImport.update({
  path: '/subscribe',
  getParentRoute: () => rootRoute,
} as any)

const PostRoute = PostImport.update({
  path: '/post',
  getParentRoute: () => rootRoute,
} as any)

const ArchetypeListRoute = ArchetypeListImport.update({
  id: '/_archetypeList',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ArchetypeIndexLazyRoute = ArchetypeIndexLazyImport.update({
  path: '/archetype/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/archetype.index.lazy').then((d) => d.Route),
)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  path: '/auth/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const ArchetypeListWordsRoute = ArchetypeListWordsImport.update({
  path: '/words',
  getParentRoute: () => ArchetypeListRoute,
} as any)

const ArchetypeListMixesRoute = ArchetypeListMixesImport.update({
  path: '/mixes',
  getParentRoute: () => ArchetypeListRoute,
} as any)

const ArchetypeListMicroRoute = ArchetypeListMicroImport.update({
  path: '/micro',
  getParentRoute: () => ArchetypeListRoute,
} as any)

const ArchetypeListLabelsRoute = ArchetypeListLabelsImport.update({
  path: '/labels',
  getParentRoute: () => ArchetypeListRoute,
} as any)

const ReadArchetypeIdRoute = ReadArchetypeIdImport.update({
  path: '/read/$archetype/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_archetypeList': {
      id: '/_archetypeList'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ArchetypeListImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostImport
      parentRoute: typeof rootRoute
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeImport
      parentRoute: typeof rootRoute
    }
    '/_archetypeList/labels': {
      id: '/_archetypeList/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof ArchetypeListLabelsImport
      parentRoute: typeof ArchetypeListImport
    }
    '/_archetypeList/micro': {
      id: '/_archetypeList/micro'
      path: '/micro'
      fullPath: '/micro'
      preLoaderRoute: typeof ArchetypeListMicroImport
      parentRoute: typeof ArchetypeListImport
    }
    '/_archetypeList/mixes': {
      id: '/_archetypeList/mixes'
      path: '/mixes'
      fullPath: '/mixes'
      preLoaderRoute: typeof ArchetypeListMixesImport
      parentRoute: typeof ArchetypeListImport
    }
    '/_archetypeList/words': {
      id: '/_archetypeList/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof ArchetypeListWordsImport
      parentRoute: typeof ArchetypeListImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/archetype/': {
      id: '/archetype/'
      path: '/archetype'
      fullPath: '/archetype'
      preLoaderRoute: typeof ArchetypeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/read/$archetype/$id': {
      id: '/read/$archetype/$id'
      path: '/read/$archetype/$id'
      fullPath: '/read/$archetype/$id'
      preLoaderRoute: typeof ReadArchetypeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ArchetypeListRouteChildren {
  ArchetypeListLabelsRoute: typeof ArchetypeListLabelsRoute
  ArchetypeListMicroRoute: typeof ArchetypeListMicroRoute
  ArchetypeListMixesRoute: typeof ArchetypeListMixesRoute
  ArchetypeListWordsRoute: typeof ArchetypeListWordsRoute
}

const ArchetypeListRouteChildren: ArchetypeListRouteChildren = {
  ArchetypeListLabelsRoute: ArchetypeListLabelsRoute,
  ArchetypeListMicroRoute: ArchetypeListMicroRoute,
  ArchetypeListMixesRoute: ArchetypeListMixesRoute,
  ArchetypeListWordsRoute: ArchetypeListWordsRoute,
}

const ArchetypeListRouteWithChildren = ArchetypeListRoute._addFileChildren(
  ArchetypeListRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ArchetypeListRouteWithChildren
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/labels': typeof ArchetypeListLabelsRoute
  '/micro': typeof ArchetypeListMicroRoute
  '/mixes': typeof ArchetypeListMixesRoute
  '/words': typeof ArchetypeListWordsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth': typeof AuthIndexRoute
  '/archetype': typeof ArchetypeIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ArchetypeListRouteWithChildren
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/labels': typeof ArchetypeListLabelsRoute
  '/micro': typeof ArchetypeListMicroRoute
  '/mixes': typeof ArchetypeListMixesRoute
  '/words': typeof ArchetypeListWordsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth': typeof AuthIndexRoute
  '/archetype': typeof ArchetypeIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_archetypeList': typeof ArchetypeListRouteWithChildren
  '/post': typeof PostRoute
  '/subscribe': typeof SubscribeRoute
  '/_archetypeList/labels': typeof ArchetypeListLabelsRoute
  '/_archetypeList/micro': typeof ArchetypeListMicroRoute
  '/_archetypeList/mixes': typeof ArchetypeListMixesRoute
  '/_archetypeList/words': typeof ArchetypeListWordsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/archetype/': typeof ArchetypeIndexLazyRoute
  '/read/$archetype/$id': typeof ReadArchetypeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/post'
    | '/subscribe'
    | '/labels'
    | '/micro'
    | '/mixes'
    | '/words'
    | '/auth/callback'
    | '/auth/verify'
    | '/auth'
    | '/archetype'
    | '/read/$archetype/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/post'
    | '/subscribe'
    | '/labels'
    | '/micro'
    | '/mixes'
    | '/words'
    | '/auth/callback'
    | '/auth/verify'
    | '/auth'
    | '/archetype'
    | '/read/$archetype/$id'
  id:
    | '__root__'
    | '/'
    | '/_archetypeList'
    | '/post'
    | '/subscribe'
    | '/_archetypeList/labels'
    | '/_archetypeList/micro'
    | '/_archetypeList/mixes'
    | '/_archetypeList/words'
    | '/auth/callback'
    | '/auth/verify'
    | '/auth/'
    | '/archetype/'
    | '/read/$archetype/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypeListRoute: typeof ArchetypeListRouteWithChildren
  PostRoute: typeof PostRoute
  SubscribeRoute: typeof SubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ArchetypeIndexLazyRoute: typeof ArchetypeIndexLazyRoute
  ReadArchetypeIdRoute: typeof ReadArchetypeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypeListRoute: ArchetypeListRouteWithChildren,
  PostRoute: PostRoute,
  SubscribeRoute: SubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
  ArchetypeIndexLazyRoute: ArchetypeIndexLazyRoute,
  ReadArchetypeIdRoute: ReadArchetypeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_archetypeList",
        "/post",
        "/subscribe",
        "/auth/callback",
        "/auth/verify",
        "/auth/",
        "/archetype/",
        "/read/$archetype/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_archetypeList": {
      "filePath": "_archetypeList.tsx",
      "children": [
        "/_archetypeList/labels",
        "/_archetypeList/micro",
        "/_archetypeList/mixes",
        "/_archetypeList/words"
      ]
    },
    "/post": {
      "filePath": "post.tsx"
    },
    "/subscribe": {
      "filePath": "subscribe.tsx"
    },
    "/_archetypeList/labels": {
      "filePath": "_archetypeList.labels.tsx",
      "parent": "/_archetypeList"
    },
    "/_archetypeList/micro": {
      "filePath": "_archetypeList.micro.tsx",
      "parent": "/_archetypeList"
    },
    "/_archetypeList/mixes": {
      "filePath": "_archetypeList.mixes.tsx",
      "parent": "/_archetypeList"
    },
    "/_archetypeList/words": {
      "filePath": "_archetypeList.words.tsx",
      "parent": "/_archetypeList"
    },
    "/auth/callback": {
      "filePath": "auth/callback.tsx"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/archetype/": {
      "filePath": "archetype.index.lazy.tsx"
    },
    "/read/$archetype/$id": {
      "filePath": "read.$archetype.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
