<script lang="ts">
  import { Schema } from 'effect'; import { onMount } from 'svelte'; import Page from '@/lib/components/dashboard/Page.svelte'; import { dashboardCommand,dashboardJson,jsonRequest } from '@/lib/components/dashboard/api'
  const Playlist=Schema.Struct({id:Schema.String,title:Schema.String,description:Schema.NullOr(Schema.String),coverImageUrl:Schema.NullOr(Schema.String),curatorId:Schema.NullOr(Schema.String),slug:Schema.String,publishedAt:Schema.NullOr(Schema.String),createdById:Schema.NullOr(Schema.String),createdAt:Schema.String,updatedAt:Schema.String,spotifyUrl:Schema.optional(Schema.NullOr(Schema.String))}); const Track=Schema.Struct({track:Schema.Struct({id:Schema.String,title:Schema.String,artistNames:Schema.NullOr(Schema.Array(Schema.String)),coverImageUrl:Schema.NullOr(Schema.String),albumId:Schema.NullOr(Schema.String),trackNumber:Schema.NullOr(Schema.Number),slug:Schema.String,publishedAt:Schema.NullOr(Schema.String),createdById:Schema.NullOr(Schema.String),createdAt:Schema.String,updatedAt:Schema.String}),position:Schema.Number,addedAt:Schema.String,links:Schema.Array(Schema.Unknown)})
  type PlaylistValue=typeof Playlist.Type; type TrackValue=typeof Track.Type; let playlists=$state<ReadonlyArray<PlaylistValue>>([]),selected=$state<PlaylistValue|null>(null),tracks=$state<ReadonlyArray<TrackValue>>([]),url=$state(''),title=$state(''),description=$state(''),coverImageUrl=$state(''),message=$state('')
  async function load(){try{playlists=await dashboardJson(Schema.Array(Playlist),'/api/music/playlists');if(selected){selected=playlists.find((item)=>item.id===selected?.id)??null}}catch{message='Could not load playlists.'}}
  async function choose(item:PlaylistValue){selected=item;title=item.title;description=item.description??'';coverImageUrl=item.coverImageUrl??'';try{tracks=await dashboardJson(Schema.Array(Track),`/api/music/playlists/${item.id}/tracks`)}catch{message='Could not load tracks.'}}
  async function save(){if(!selected)return;try{selected=await dashboardJson(Playlist,`/api/music/playlists/${selected.id}`,jsonRequest('PATCH',{title,description:description||null,coverImageUrl:coverImageUrl||null}));await load();message='Playlist saved.'}catch{message='Could not save playlist.'}}
  async function importPlaylist(){try{await dashboardJson(Schema.Unknown,'/api/music/playlists/import/spotify',jsonRequest('POST',{url}));url='';await load();message='Playlist imported.'}catch{message='Import failed.'}}
  async function remove(track:TrackValue){if(!selected||!confirm(`Remove ${track.track.title}?`))return;await dashboardCommand(`/api/music/playlists/${selected.id}/tracks/${track.track.id}`,{method:'DELETE'});await choose(selected)}
  async function move(index:number,delta:number){if(!selected)return;const next=[...tracks],target=index+delta;if(target<0||target>=next.length)return;const current=next[index],other=next[target];if(!current||!other)return;next[index]=other;next[target]=current;tracks=next;await dashboardCommand(`/api/music/playlists/${selected.id}/tracks/order`,jsonRequest('PUT',{trackIds:next.map((row)=>row.track.id)}))}
  onMount(load)
</script>
<Page title="Playlist Management" description="Import playlists, edit metadata, and curate track order."><form class="flex gap-2 rounded border p-4" onsubmit={(e)=>{e.preventDefault();void importPlaylist()}}><input required type="url" class="w-full rounded border bg-background p-2" placeholder="Spotify playlist URL" bind:value={url}/><button class="rounded bg-foreground px-4 text-background">Import</button></form><div class="grid gap-6 lg:grid-cols-[16rem_1fr]"><aside class="rounded border">{#each playlists as playlist}<button class="block w-full border-b p-3 text-left hover:bg-muted" onclick={()=>void choose(playlist)}><strong>{playlist.title}</strong><span class="block text-xs text-muted-foreground">{playlist.slug}</span></button>{/each}</aside>{#if selected}<main class="space-y-4"><form class="grid gap-3 rounded border p-4" onsubmit={(e)=>{e.preventDefault();void save()}}><label>Title<input required class="block w-full rounded border bg-background p-2" bind:value={title}/></label><label>Description<textarea class="block w-full rounded border bg-background p-2" bind:value={description}></textarea></label><label>Cover image URL<input class="block w-full rounded border bg-background p-2" bind:value={coverImageUrl}/></label><button class="w-fit rounded bg-foreground px-4 py-2 text-background">Save metadata</button></form><div class="rounded border">{#each tracks as track,index}<div class="flex items-center gap-3 border-b p-3"><span class="w-6">{index+1}</span><div class="min-w-0 flex-1"><strong>{track.track.title}</strong><span class="block truncate text-xs text-muted-foreground">{track.track.artistNames?.join(', ')??'Unknown artist'}</span></div><button aria-label="Move up" disabled={index===0} onclick={()=>void move(index,-1)}>↑</button><button aria-label="Move down" disabled={index===tracks.length-1} onclick={()=>void move(index,1)}>↓</button><button class="text-destructive underline" onclick={()=>void remove(track)}>Remove</button></div>{/each}{#if tracks.length===0}<p class="p-4 text-muted-foreground">No tracks.</p>{/if}</div></main>{:else}<p class="text-muted-foreground">Select a playlist to edit.</p>{/if}</div>{#if message}<p>{message}</p>{/if}</Page>
