<script lang="ts">
  import { Schema } from 'effect'; import { onMount } from 'svelte'; import Page from '@/lib/components/dashboard/Page.svelte'; import { dashboardJson,jsonRequest } from '@/lib/components/dashboard/api'
  const Role=Schema.Literals(['user','creator','editor','admin']); const User=Schema.Struct({id:Schema.String,name:Schema.String,email:Schema.String,role:Schema.NullOr(Schema.String),banned:Schema.optional(Schema.Boolean),banReason:Schema.optional(Schema.NullOr(Schema.String)),emailVerified:Schema.Boolean}); const Result=Schema.Struct({users:Schema.Array(User),total:Schema.Number,limit:Schema.Number})
  type UserValue=typeof User.Type; type RoleValue=typeof Role.Type
  let users=$state<ReadonlyArray<UserValue>>([]),search=$state(''),offset=$state(0),total=$state(0),message=$state(''),name=$state(''),email=$state(''),password=$state(''),role=$state<RoleValue>('user'); const limit=25
  async function load(){message='';try{const query=new URLSearchParams({limit:String(limit),offset:String(offset)});if(search)query.set('searchValue',search),query.set('searchField','email');const r=await dashboardJson(Result,`/auth/admin/list-users?${query}`);users=r.users;total=r.total}catch{message='Could not load users.'}}
  async function command(path:string,body:Schema.Json){try{await dashboardJson(Schema.Unknown,`/auth/admin/${path}`,jsonRequest('POST',body));message='Account updated.';await load()}catch{message='Account action failed.'}}
  async function create(){await command('create-user',{name,email,password,role});name='';email='';password=''}
  async function remove(user:UserValue){if(confirm(`Permanently delete ${user.name}? This cannot be undone.`))await command('remove-user',{userId:user.id})}
  function ban(userId:string){const reason=prompt('Ban reason (optional)');void command('ban-user',reason?{userId,banReason:reason}:{userId})}
  onMount(load)
</script>
<Page title="Users" description="Search accounts, manage access, and onboard users.">
  <form class="flex gap-2" onsubmit={(e)=>{e.preventDefault();offset=0;void load()}}><input class="w-full max-w-sm rounded border bg-background p-2" type="search" placeholder="Search by email" bind:value={search}/><button class="rounded border px-4">Search</button></form>
  <form class="grid gap-3 rounded border p-4 sm:grid-cols-5" onsubmit={(e)=>{e.preventDefault();void create()}}><input required class="rounded border bg-background p-2" placeholder="Display name" bind:value={name}/><input required class="rounded border bg-background p-2" type="email" placeholder="Email" bind:value={email}/><input required minlength="8" class="rounded border bg-background p-2" type="password" placeholder="Temporary password" bind:value={password}/><select class="rounded border bg-background p-2" bind:value={role}>{#each ['user','creator','editor','admin'] as item}<option>{item}</option>{/each}</select><button class="rounded bg-foreground px-4 text-background">Create user</button></form>
  <div class="overflow-x-auto rounded border"><table class="w-full text-left text-sm"><thead><tr class="bg-muted"><th class="p-3">Name</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{#each users as user}<tr class="border-t"><td class="p-3">{user.name}</td><td>{user.email}</td><td><select class="rounded border bg-background p-1" value={user.role??'user'} onchange={(e)=>{const next=Schema.decodeUnknownOption(Role)(e.currentTarget.value);if(next._tag==='Some')void command('set-role',{userId:user.id,role:next.value})}}>{#each ['user','creator','editor','admin'] as item}<option>{item}</option>{/each}</select></td><td>{user.banned?'Banned':'Active'}</td><td class="space-x-3">{#if user.banned}<button class="underline" onclick={()=>void command('unban-user',{userId:user.id})}>Unban</button>{:else}<button class="underline" onclick={()=>ban(user.id)}>Ban</button>{/if}<button class="underline" onclick={()=>void fetch('/api/invite/send',jsonRequest('POST',{userId:user.id}))}>Invite</button><button class="text-destructive underline" onclick={()=>void remove(user)}>Delete</button></td></tr>{/each}</tbody></table></div>
  <div class="flex justify-between"><button disabled={offset===0} onclick={()=>{offset=Math.max(0,offset-limit);void load()}}>Previous</button><span>{offset+1}–{Math.min(total,offset+users.length)} of {total}</span><button disabled={offset+users.length>=total} onclick={()=>{offset+=limit;void load()}}>Next</button></div>{#if message}<p aria-live="polite">{message}</p>{/if}
</Page>
