name: Release

on:
  push:
    branches:
      - prod

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Get Next Version
        id: versioning
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: prod
          patchList: fix, bugfix, perf, refactor, test, tests, ci, docs, chore

      - name: Update package.jsons
        run: |
          bun pm version ${{ steps.versioning.outputs.nextStrict }} --no-git-tag-version
          cd web && bun pm version ${{ steps.versioning.outputs.nextStrict }} --no-git-tag-version

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "The Machine🤖"
          git add .
          git commit -m "chore: bump package version to ${{ steps.versioning.outputs.nextStrict }}"
          git tag -a "${{ steps.versioning.outputs.nextStrict }}" -m "Release ${{ steps.versioning.outputs.nextStrict }}"
          git push origin prod
          git push origin "${{ steps.versioning.outputs.nextStrict }}"

      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: "${{ steps.versioning.outputs.nextStrict }}"
      #     name: "Release ${{ steps.versioning.outputs.nextStrict }}"
      #     body: "Automated release notes"
