# name: sst

# on:
#   push:
#     branches:
#       - prod
#       - staging

# concurrency: 
#   group: ${{ github.ref }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - uses: actions/cache@v2
#         with:
#           path: |
#             .sst
#           key: ${{ runner.os }}-sst

#       - uses: oven-sh/setup-bun@v1
#         with:
#           bun-version: latest

#       - uses: actions/setup-node@v1
#         with:
#           node-version: "20"

#       - name: Configure Production AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-to-assume: ${{secrets.AWS_ROLE_ARN}}
#           role-duration-seconds: 3600 #adjust as needed for your build time
#           aws-region: us-east-1

#       - name: deps
#         run: bun install

#       # - name: typecheck
#       #   run: bun typecheck

#       - name: Deploy
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           CLOUDFLARE_DEFAULT_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_DEFAULT_ACCOUNT_ID }}
#           SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
#           SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
#           SQUEAL_DB_URL: ${{ secrets.SQUEAL_DB_URL }}

#         run: |
#           bun run sst refresh --stage=${GITHUB_REF_NAME}
#           bun run sst deploy --stage=${GITHUB_REF_NAME}
